### PR TITLE
Add some integration tests

### PR DESCRIPTION
**Pull request by pierd**
.. to encourage testing and start stabilising the app a bit.

Integration testing: https://guides.rubyonrails.org/testing.html#integration-testing

### CODE REVIEW

**Comment by dav-armour** [comment]
Will need to learn how to write integration test. Have only done RSpec testing before. Have next week off class so should have time to learn then.

**Review by dav-armour — APPROVED** [review]
I presume these all work. Will leave it up to you if it's ready to merge

**Comment by pierd** [comment]
@dav-armour one test is currently broken because registration is broken:
```
Error:
BasicFlowsTest#test_can_see_the_sign-up_page_with_a_form:
ActionController::RoutingError: uninitialized constant RegistrationsController
    test/integration/basic_flows_test.rb:19:in `block in <class:BasicFlowsTest>'
```

**Comment by pierd** [comment]
Also I'm not sure how to put paths in programmatic way. Now they are hardcoded so any change to routes breaks the tests.

@dav-armour I'll wait for you to fix the registration before merging this in.

**Comment by pierd** [comment]
Simple tests but already useful - just saying 😝 

These tests would prevent a broken heroku deployment: http://umbo.herokuapp.com/register

**Comment by dav-armour** [comment]
> Also I'm not sure how to put paths in programmatic way. Now they are hardcoded so any change to routes breaks the tests.

@pierd Have changed the tests to use programmatic path. Run rails routes > look at prefix in left hand column. Then it is just prefix_path

routes

**Pull request merged**
